"""empty message

Revision ID: 6310378df89b
Revises: 
Create Date: 2026-03-20 20:19:48.184289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6310378df89b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parrain_uid', sa.String(length=200), nullable=False),
    sa.Column('filleul_uid', sa.String(length=200), nullable=False),
    sa.Column('montant', sa.Float(), nullable=False),
    sa.Column('niveau', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=255), nullable=False),
    sa.Column('correct_answer', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('retrait',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('montant', sa.Float(), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('pays', sa.String(length=50), nullable=True),
    sa.Column('frais', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('vip_level', sa.String(length=20), nullable=False),
    sa.Column('montant', sa.Float(), nullable=False),
    sa.Column('duree', sa.Integer(), nullable=True),
    sa.Column('taux_min', sa.Float(), nullable=True),
    sa.Column('taux_max', sa.Float(), nullable=True),
    sa.Column('revenu_total', sa.Float(), nullable=False),
    sa.Column('date_debut', sa.DateTime(), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=300), nullable=False),
    sa.Column('parrain', sa.String(length=50), nullable=True),
    sa.Column('has_played_slot', sa.Boolean(), nullable=True),
    sa.Column('commission_total', sa.Float(), nullable=True),
    sa.Column('has_seen_pay_ok', sa.Boolean(), nullable=True),
    sa.Column('wallet_country', sa.String(length=50), nullable=True),
    sa.Column('wallet_operator', sa.String(length=50), nullable=True),
    sa.Column('wallet_number', sa.String(length=30), nullable=True),
    sa.Column('bonus', sa.Float(), nullable=True),
    sa.Column('solde_total', sa.Float(), nullable=True),
    sa.Column('solde_depot', sa.Float(), nullable=True),
    sa.Column('solde_parrainage', sa.Float(), nullable=True),
    sa.Column('solde_revenu', sa.Float(), nullable=True),
    sa.Column('total_retrait', sa.Float(), nullable=True),
    sa.Column('premier_depot', sa.Boolean(), nullable=True),
    sa.Column('has_free_attempt', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_banned', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('has_frog_attempt', sa.Boolean(), nullable=True),
    sa.Column('frog_game_done', sa.Boolean(), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('points_video', sa.Integer(), nullable=True),
    sa.Column('points_youtube', sa.Integer(), nullable=True),
    sa.Column('points_tiktok', sa.Integer(), nullable=True),
    sa.Column('points_instagram', sa.Integer(), nullable=True),
    sa.Column('points_ads', sa.Integer(), nullable=True),
    sa.Column('points_spin', sa.Integer(), nullable=True),
    sa.Column('points_games', sa.Integer(), nullable=True),
    sa.Column('last_instagram_date', sa.String(length=10), nullable=True),
    sa.Column('last_youtube_date', sa.String(length=10), nullable=True),
    sa.Column('last_tiktok_date', sa.String(length=20), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('login_count', sa.Integer(), nullable=True),
    sa.Column('has_spun_wheel', sa.Boolean(), nullable=True),
    sa.Column('has_spun', sa.Boolean(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('date_update', sa.DateTime(), nullable=True),
    sa.Column('solde_jeux', sa.Float(), nullable=True),
    sa.Column('whatsapp_number', sa.String(length=30), nullable=True),
    sa.Column('profile_pic', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['parrain'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('uid'),
    sa.UniqueConstraint('username')
    )
    op.create_table('click_jeudi_reponse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('click_tache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('depot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('operator', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('montant', sa.Float(), nullable=False),
    sa.Column('reference', sa.String(length=200), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_name'], ['user.username'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('bet_amount', sa.Integer(), nullable=True),
    sa.Column('win_amount', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_reponse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('retrait_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('points_utilises', sa.Integer(), nullable=False),
    sa.Column('montant_xof', sa.Float(), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('retrait_points')
    op.drop_table('question_reponse')
    op.drop_table('game_session')
    op.drop_table('depot')
    op.drop_table('click_tache')
    op.drop_table('click_jeudi_reponse')
    op.drop_table('user')
    op.drop_table('staking')
    op.drop_table('retrait')
    op.drop_table('question')
    op.drop_table('commission')
    # ### end Alembic commands ###
