"""ajout capture depot

Revision ID: 9fadf92c36ac
Revises: 6310378df89b
Create Date: 2026-04-12 17:17:57.899581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fadf92c36ac'
down_revision = '6310378df89b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('depot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('capture', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('depot', schema=None) as batch_op:
        batch_op.drop_column('capture')

    # ### end Alembic commands ###
